### ISSUE TITLE
[illegal_argument_exception] mapper [hits] cannot be changed from type [long] to [int]

### ISSUE THREAD

**Issue by Eagleman7** [StamusNetworks/KTS#1]
After applying patches and importing dashboards using your script I am still getting:

[illegal_argument_exception] mapper [hits] cannot be changed from type [long] to [int]

I included a picture because I am unsure which visualization is causing it:
[http://i.imgur.com/vXmSnTn.png](http://i.imgur.com/vXmSnTn.png)

I did restart

**Comment by Eagleman7** [comment]
This happens on every dashboards page, there is one visualization that shows this warning.

**Comment by pevma** [comment]
What is the name of the visualization ?

**Comment by Eagleman7** [comment]
It starts with the dashboard name and then -EventsList.

DNS-EventsList
HTTP-EventsList
ALERT-EventsList
.........

This is the link when I try to edit it: http://192.168.1.22:5601/app/kibana#settings/objects/savedSearches/HTTP-EventsList?notFound=undefined

Once I edit it I get this: http://i.imgur.com/H6f7o9B.png

**Comment by pevma** [comment]
ok - but when you try to edit - you should see the name of the visualization. Would you be able to see that?

**Comment by Eagleman7** [comment]
When I edit I am getting an error: http://i.imgur.com/H6f7o9B.png

**Comment by pevma** [comment]
Ok.
And that err happens only with this dashboard when you edit or with any other as well?

**Comment by pevma** [comment]
Fixed now - thanks for the feedback !
