### ISSUE TITLE
the timelion-integer.patch cannot be patched

### ISSUE THREAD

**Issue by superhobbit** [StamusNetworks/KTS#5]
I write the right command and the right path,change the -pN for several times,but it still gives the error,the kibana-integer.patch patch successfully but the second one failed.The error shows this:
`can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
## The text leading up to this was:

|diff -u -r kibana-4.3.1-linux-x64-1/installedPlugins/timelion/public/services/_saved_sheet.js kibana-4.3.1-linux-x64-2/installedPlugins/timelion/public/services/_saved_sheet.js
|--- kibana-4.3.1-linux-x64-1/installedPlugins/timelion/public/services/_saved_sheet.js 2016-01-26 11:09:49.093222555 +0100
## |+++ kibana-4.3.1-linux-x64-2/installedPlugins/timelion/public/services/_saved_sheet.js 2016-01-25 17:37:55.007695074 +0100

File to patch: 
Skip this patch? [y] y
Skipping patch.
1 out of 1 hunk ignored
`

**Comment by pevma** [comment]
What is your command exactly?

**Comment by superhobbit** [comment]
Thanks for replying!Here it is:
`patch -p1 -d /var/www/kibana-4.5.0-linux-x64/  < /home/hobbit/KTS/patches/timelion-integer.patch
`

**Comment by superhobbit** [comment]
I know what happened...it's because i didn't install the timelion plugin,after I install it everything goes well.
